<a href="https://colab.research.google.com/github/sahintarkan/DA_Statistics/blob/master/01_Stats_Assign_F1498(Central_Tendency%26_Dispersion)_bos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
np.random.seed(1)
samples =np.random.normal(loc=100, scale=15,size=1000)
samples

array([124.36518045,  90.8236538 ,  92.07742372,  83.90547067,
       112.98111444,  65.47691955, 126.17217646,  88.58189649,
       104.78558644,  96.25944437, 121.93161906,  69.09788936,
        95.16374194,  94.23918468, 117.00654164,  83.50163099,
        97.41357689,  86.83212373, 100.6332062 , 108.74222821,
        83.49071234, 117.17085565, 113.52386081, 107.53741508,
       113.51283924,  89.74408211,  98.15664662,  85.96345849,
        95.98167881, 107.955332  ,  89.62508872,  94.0486971 ,
        89.6924095 ,  87.32191538,  89.93130804,  99.81003102,
        83.24034477, 103.51623547, 124.89703266, 111.13066241,
        97.12246671,  86.68556554,  88.79262559, 125.38681902,
       100.76211632,  90.4450653 , 102.86373227, 131.50382705,
       101.80238429, 109.25804665, 104.5025548 ,  94.7162523 ,
        82.86222703,  94.75985916,  96.8665865 , 108.79934787,
       112.58475121, 113.96653122, 104.28380988, 113.27711746,
        88.68403089, 118.79302233, 107.69394731,  95.52

Compute the **mean**, **median**, and **mode**

In [12]:
mean=samples.mean()
median=np.median(samples)
mode=stats.mode(samples)
print(mean,median,mode)

100.58218714239403 100.61938883303824 ModeResult(mode=array([54.19353429]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [14]:
min = samples.min()
max =samples.max()
q1 =np.percentile(samples, 25)
q3 =np.percentile(samples, 75)
iqr =stats.iqr(samples)

In [15]:
min , max , iqr , q1 , q3

(54.193534293605424,
 159.37904056056945,
 19.562389286089342,
 90.99759351968441,
 110.55998280577376)

Compute the **variance** and **standard deviation**

In [16]:
variance = np.var(samples)
std_dev =np.std(samples)

In [17]:
variance , std_dev , np.sqrt , np.square

(216.53304992821992, 14.715062008983175)

Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [19]:
skewness =stats.skew(samples)
kurtosis =stats.kurtosis(samples)

In [20]:
skewness , kurtosis

(-0.06835228125486917, 0.23360137518812696)

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [22]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [26]:
y = np.random.randint(1,100 , 10)
y

array([34, 37, 10,  1, 56, 70, 11,  4, 40, 78])

In [27]:
np.random.seed(5)
y = np.random.randint(1,100 , 10)
y

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [29]:
r = np.corrcoef(x,y)
r

array([[ 1.        , -0.32329532],
       [-0.32329532,  1.        ]])

In [34]:
r=stats.pearsonr(x,y)
r

(-0.32329532278115697, 0.362188680125618)

## Pandas Correlation Calculation

Run the code below

In [35]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [37]:
r=stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

Call the relevant method  to calculate Pearson's r correlation.

In [32]:
r =stats.pearsonr(x,y)
r

(-0.32329532278115697, 0.362188680125618)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [39]:
rho =stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import 

Load "tips" dataset from Seaborn

In [41]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [42]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [43]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000